### ISSUE TITLE
FreeBSD compatibility

### ISSUE THREAD

**Issue by mimugmail** [fln/addrwatch#19] opened 2020-02-21 20:17 UTC
Hi,

I'm trying to compile this software on FreeBSD and it seems to work fine with some workaround:

`./configure LDFLAGS="-L/usr/local/lib" CPPFLAGS="-I/usr/local/include"`

But after `make && make install` and executing addrwatch I get:

root@build:/usr/ports/net/addrwatch/work/addrwatch-86e9ec5 # /usr/local/test/bin/addrwatch -v em0
addrwatch: DEBUG: Duplicate entries ratelimiting disabled
addrwatch: DEBUG: PROMISC mode enabled
addrwatch: DEBUG: Opened interface em0 (Ethernet)
addrwatch: ERR: Error creating shared memory

Is there a known limitation for FreeBSD?

**Comment by fln** [comment] 2020-02-23 12:10
Hi,

This package was not tested for compatibility with FreeBSD. It seems the issue is caused by the FreeBSD restriction on shared memory segment names. FreeBSD requires it to start with `/` symbol.

A quick fix for this issue pushed to the master. Please check if release 59a075e works for you.

**Closed by fln** 2020-02-23 12:10 UTC

**Comment by mimugmail** [comment] 2020-02-24 08:21
Thanks! I added a PR for adding it to FreeBSD ports:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244359
